name: Test
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  Test:
    runs-on: [natu--sifferman-macos-runner]
    steps:
      - uses: actions/checkout@v3
      - name: Install Tools
        run: |
          brew update
          find ~ -type d
          find / -type d 2>/dev/null
          brew update
